name: RYSH_BOT
run-name: ${{ github.actor }} is building RYSH_BOT Project
on: [push]
jobs:
  RYSH_BOT:
    runs-on: [self-hosted]
    env:
      working-directory: .
    steps:
      - uses: actions/checkout@v2
      - run: ls
      - run: cp ChatGPT.js /node/ChatGPT.js
      - run: cp expressPort.js /node/expressPort.js
      - run: cp QQBot.js /node/QQBot.js
      - run: pm2 start index.js
      - run: pm2 save
