name: RYSH_BOT
run-name: ${{ github.actor }} is building RYSH_BOT Project
on: [push]
jobs:
  RYSH_BOT:
    runs-on: [self-hosted]
    env:
      working-directory: .
    steps:
      - uses: actions/checkout@v2
      - run: ls
      - run: cp rysh_bot.js /node/rysh_bot.js
      - run: pm2 restart 5
